Convert orientations to old matflow format
I still get this error that I got before converting to old matflow
orientations format:

```
  File "/home/mbexegc2/projects/lightform/cipher-workflows/cipher-aiden_2025-10-29_133031/artifacts/submissions/0/scripts/generate_volume_element_from_statistics_dual_phase_orientations_Dream3D_act_3.py", line 40, in parse_dream_3D_volume_element_from_stats
    ori_1 = validate_orientations(orientations_phase_1)
  File "/home/mbexegc2/projects/lightform/cipher-workflows/.venv/lib/python3.10/site-packages/damask_parse/utils.py", line 983, in validate_orientations
    ori_type = orientations.get('type')
AttributeError: 'Orientations' object has no attribute 'get'
```